export const routes = {
  home: '/',
  marketplace: '/opportunities',
  login: '/auth/login',
  register: '/auth/register',
  investorDashboard: '/investor/dashboard',
  investments: '/investor/investments',
  portfolio: '/investor/portfolio',
  wallet: '/investor/wallet',
  profile: '/investor/profile',
  companyDashboard: '/company/dashboard',
  companyProjects: '/company/projects',
  adminDashboard: '/admin',
  opportunity: (id: string) => `/opportunities/${encodeURIComponent(id)}`,
  investment: (id: string) => `/investor/investments/${encodeURIComponent(id)}`,
  companyProject: (id: string) => `/company/projects/${encodeURIComponent(id)}`,
} as const
